export const ApiUrl = {
    LOGIN: 'admin/login',
    REGISTER: 'admin/register',
    CONTACTS: 'contact/getContacts',
    ADD_FILTER: 'contact/addEditFilterList',
    ADD_CONTACT: 'contact/addEditContacts',
    SEND_EMAIL: 'admin/sendEmail',
    DASHBOARD: 'admin/dashboard',
    CHANGE_PASSWORD: 'admin/changePassword',
    FORGOT_PASSWORD: 'admin/forgotPassword',
    UPLOAD_IMAGE: 'api/uploadImage',
    CONTACT_DETAILS: 'contact/contactDetails',
    EMAIL_HISTORY: 'admin/getEmailHistory',
    ACTIVITY_LIST: 'admin/getActivity',
    ADD_EDIT_NOTES: 'admin/addEditNotes',
    IMPORT_CONTACT: 'contact/importContacts',
    NOTES: 'admin/listNotes',
    DELETE_DATA: 'admin/deleteData',
    EXPORT_CONTACTS: 'contact/exportContacts',
    ADD_FILES: 'contact/addEditFiles',
    LIST_FILES: 'contact/listFiles',
    CONTACT_LISTS: 'contact/getContactList',
    CREATE_CONTACT_GROUP: 'contacts/create-group',
    UPDATE_CONTACT_GROUP: 'contact/modify-group',
    ADD_TASK: 'task/addEditTasks',
    ADD_USER: 'admin/addEditSubUser',
    TASK_LIST: 'task/getTasks',
    USER_LIST: 'admin/listSubUsers',
    TAGS: 'admin/listTags',
    ADD_TAG_TO_CONTACT: 'contact/addTagsToContact',
    REMOVE_TAG_FROM_CONTACT: 'contact/removeTagFromContact',
    ADD_TAG: 'admin/addEditTag',
    ADD_TAG_CATEGORY: 'admin/addEditTagCategory',
    TAG_CATEGORIES: 'admin/listTagCategory',
    UPDATE_TASK: 'task/updateStatus',
    ADD_EMAIL_TEMPLATE: 'admin/addEditEmailTemplates',
    TEMPLATE_LIST: 'admin/listEmailTemplates',
    DELETE_IMAGE: 'api/deleteImageBucket',
    CONTACT_TAGS: 'contact/getContactTags',
    PRODUCTS: 'money/listProducts',
    testPush: 'money/testPush',
    ADD_PRODUCT: 'money/addEditProducts',
    ADD_PAYMENT: 'money/addPayments',
    PAYMENT_LIST: 'money/listPayments',
    QUOTES_LIST: 'money/listInvoiceQuotes',
    BUSINESS_LIST_TYPE: 'money/listBusinessType',
    ADD_ADDRESS: 'money/addEditBusinessAddress',
    COUNTRY_STATE: 'admin/countryState',
    ADDRESS_LIST: 'money/listBusinessAddress',
    ADD_INVOICE: 'money/addEditInvoiceQuote',
    SET_DEFAULT_ADDRESS: 'money/setDefaultAddress',
    ACCEPT_QUOTE: 'money/acceptInvoiceQuote',
    INVOICE_DETAILS: 'money/invoiceQuoteDetails',
    CONVERT_TO_INVOICE: 'money/convertToInvoice',
    ADD_BROADCAST: 'broadcast/addEditBroadcast',
    COPY_BROADCAST: 'broadcast/copyBroadcast',
    BROADCAST_LIST: 'broadcast/listBroadcast',
    ADD_PIPELINE: 'pipeline/addEditPipeline',
    PIPELINES: 'pipeline/getPipeline',
    DELETE_PIPELINE: 'pipeline/deletePipeline',
    PIPELINE_STAGES: 'pipeline/getPipelineStages',
    ADD_DEAL: 'pipeline/addEditDeal',
    ADD_DEAL_NOTE: 'pipeline/addEditDealNote',
    ADD_PIPELINE_STAGE: 'pipeline/addEditPipelineStage',
    DELETE_PIPELINE_STAGE: 'pipeline/deleteStagePipeline',
    REORDER_STAGE: 'pipeline/reorderStage',
    MOVE_DEAL: 'pipeline/moveDeal',
    DELETE_DEAL: 'pipeline/deleteDeal',
    DEAL_DETAILS: 'pipeline/dealDetails',
    DEAL_NOTES: 'pipeline/getDealNotes',
    DELETE_DEAL_NOTES: 'pipeline/deleteNote',
    CONFIGURE_AUTOMATION: 'pipeline/configureAutomation',
    STAGE_AUTOMATION_DETAILS: 'pipeline/getStageAutomation',
    ADD_APPOINTMENT_TYPE: 'appointment/addEditAppointmentType',
    APPOINTMENT_LIST_TYPES: 'appointment/listTypes',
    UPDATE_PROFILE: 'admin/updateProfile',
    DELETE_APPOINT_TYPE: 'appointment/deleteType',
    APPOINT_BOOK_NOW: 'appointment/bookNow',
    LIST_SLOTS: 'appointment/listSlots',
    BOOK_NOW_OUTSIDE: 'appointment/bookNowOutside',
    CHECK_UNIQUE: 'appointment/checkUnique',
    APPOINTMENTS: 'appointment/listAppointments',
    NOTIFICATIONS: 'admin/listNotifications',
    UPDATE_TOKEN:'admin/updateDeviceToken',

    // chat api's
    CHAT_CONTACT_DATA: 'chat/fetch-contacts',
    CHAT_GROUP_DATA: 'chat/fetch-contactlists',
    CHAT_ROOM: 'chat/fetch-chatrooms',
    CHAT_MSG:'chat/fetch-messages',
    CREATE_CHATROOM : 'chat/create-chatroom',
    PIN_MSG : 'chat/pin',
    UNPIN_MSG : 'chat/unpin',
    SEND_IMAGE : 'chat/chat-file-message',
    MSG_SEARCH : 'chat/fetch-messages',
    PROFILE_PIN_MSG : 'chat/fetch-pinned-messages',
    CLEAR_CHAT : 'chat/clear-chat',
    BLOCK_USER : 'chat/block-user',
    UNBLOCK_USER : 'chat/unblock-user',
    CUR_USER : 'chat/me',
    FETCH_BLOCK_USERS : 'chat/fetch-blocked-users',
    DELETE_CHATROOM : 'chat/delete-chatroom',
    CALL_LOG : 'chat/calls',

    //Workspace api's
    WORKSPACE: 'workspaces',
    USERWORKSPACE:'users/workspaces',
    WORKSPACE_MERGE: 'workspaces/merge',
    WORKSPACE_SET_ACTIVE: 'workspaces/set-active',

    // Automations Api's
    GET_AUTOMATIONS : 'automation/get-automations',
    DELETE_AUTOMATION : 'automation/delete-automation',
    ADD_AUTOMATION : 'automation/add-automation-event',

    GET_THEN_EVENTS: 'automation/then-events',
    GET_WHEN_EVENTS: 'automation/when-events'
};

